name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./schedule-backend
          file: ./schedule-backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/schedule-backend:${{ env.TAG }}

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./schedule-frontend
          file: ./schedule-frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/schedule-frontend:${{ env.TAG }}

      - name: Deploy to AWS via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          envs: TAG,DOCKER_HUB_USERNAME
          script: |
            sudo bash -c '
              cd /home/ubuntu/Devops
              git pull origin main
              sed -i "s|\${DOCKER_HUB_USERNAME}/schedule-backend.*|\${DOCKER_HUB_USERNAME}/schedule-backend:\$TAG|" docker-compose-prod.yml
              sed -i "s|\${DOCKER_HUB_USERNAME}/schedule-frontend.*|\${DOCKER_HUB_USERNAME}/schedule-frontend:\$TAG|" docker-compose-prod.yml
              docker compose -f docker-compose-prod.yml pull
              docker compose -f docker-compose-prod.yml down
              docker compose -f docker-compose-prod.yml up -d --remove-orphans
            '
