name: Build and Deploy to AWS

on:
  push:
    branches:
      - main

env:
  TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/schedule-backend:$TAG ./backend

      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/schedule-frontend:$TAG ./frontend

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/schedule-backend:$TAG

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/schedule-frontend:$TAG

      - name: Deploy to AWS via SSH as root
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          envs: TAG,DOCKER_HUB_USERNAME
          script: |
            sudo bash -c '
              cd /home/ubuntu/Devops
              git pull origin main
              sed -i "s|${DOCKER_HUB_USERNAME}/schedule-backend.*|${DOCKER_HUB_USERNAME}/schedule-backend:$TAG|" docker-compose-prod.yml
              sed -i "s|${DOCKER_HUB_USERNAME}/schedule-frontend.*|${DOCKER_HUB_USERNAME}/schedule-frontend:$TAG|" docker-compose-prod.yml
              docker compose -f docker-compose-prod.yml pull
              docker compose -f docker-compose-prod.yml down
              docker compose -f docker-compose-prod.yml up -d --remove-orphans
            '
